apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rbac-test
  name: pod-reader
rules:
- apiGroups: [""] # The core API group where Pods live
  resources: ["pods"]
  verbs: ["get", "list", "watch"]