apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: rbac-secret-demo-
spec:
  pipelineRef:
    name: rbac-secret-demo
  # Link the service account (which has git-basic-auth and registry-credentials)
  taskRunTemplate:
    serviceAccountName: pipeline-runner
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
