apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: subpath-demo-
spec:
  pipelineRef:
    name: subpath-demo
  workspaces:
    - name: resources
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
