apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: bundle-demo-
spec:
  pipelineRef:
    name: bundle-demo
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
